#!/bin/bash
#
# This script builds dynamic WalletCore and VSwiftProtobuf xcframework for SPM and CocoaPods
#

set -e

echo "Building Docc..."
tools/ios-doc

echo "Building xcframework..."
pushd swift
fastlane ios xcframework
popd
