#!/bin/bash

set -e

source "$(dirname $0)/parse_args" "$@"
source "$(dirname $0)/android-sdk"

TARGET_NAME="libwallet_core_rs.a"
TARGET_XCFRAMEWORK_NAME=../swift/WalletCoreRs.xcframework
BUILD_FOLDER=../rust/target
CRATE="wallet-core-rs"
HEADER_NAME="WalletCoreRSBindgen.h"

create_xc_framework() {
  rm -rf $TARGET_XCFRAMEWORK_NAME
  xcodebuild -create-xcframework \
    -library $BUILD_FOLDER/aarch64-apple-visionos/release/$TARGET_NAME \
    -library $BUILD_FOLDER/aarch64-apple-visionos-sim/release/$TARGET_NAME \
    -output $TARGET_XCFRAMEWORK_NAME
}

cd rust

export RUSTFLAGS="-Zlocation-detail=none"

if isTargetSpecified "ios" && [[ $(uname) == "Darwin" ]]; then
  cargo clean
  cargo update
  echo "Generating iOS targets"
  cargo +nightly build -Z build-std=std,panic_abort --target aarch64-apple-visionos \
    --target aarch64-apple-visionos-sim \
    --release --lib &
  wait
  create_xc_framework
fi

cbindgen --crate $CRATE --output ../src/rust/bindgen/$HEADER_NAME
cd -
[[ -e rust/target/release/${TARGET_NAME} ]] && cp rust/target/release/${TARGET_NAME} build/local/lib/

echo "Generating C++ files..."
pushd codegen-v2 && cargo run -- cpp && popd